package repository

import (
	"log"
	database "websocket_server/config"
)

type ChatRepository interface {
	SetChats(senderID, receiverID, message string) (string, error)
}

type ChatDB struct {
	sqlDB *database.PostgreDB
}

func InitChatRepository(db *database.PostgreDB) *ChatDB {
	return &ChatDB{
		sqlDB: db,
	}
}

func (r *ChatDB) SetChats(senderID, receiverID, message string) (string, error) {
	tx, err := r.sqlDB.Db.Begin()
	if err != nil {
		return "", err
	}
	defer tx.Rollback()

	var chatID string

<<<<<<< HEAD
	log.Printf("Sender Id: %s\nReceiver Id: %s\n Message: %s", senderID, receiverID, message)

=======
>>>>>>> 36d353e870a3a92512049044059065c65fef7165
	findQuery := `
        SELECT chat_id FROM chat_participants 
		WHERE chat_id IN (
			SELECT chat_id FROM chat_participants WHERE user_id = $1
		) AND user_id = $2
		GROUP BY chat_id
    `
	err = tx.QueryRow(findQuery, senderID, receiverID).Scan(&chatID)

	if err == nil {
		// 2. CHAT EXISTS: Just update the last message
		updateQuery := `UPDATE chats SET last_message = $1, updated_at = NOW() WHERE chat_id = $2`
		if _, err := tx.Exec(updateQuery, message, chatID); err != nil {
			return "", err
		}

	} else {
		// 3. CHAT DOES NOT EXIST: Create everything
		// Note: chat_id is auto-generated by UUID default in the table
		insertChat := `INSERT INTO chats (last_message) VALUES ($1) RETURNING chat_id`
		if err := tx.QueryRow(insertChat, message).Scan(&chatID); err != nil {
			return "", err
		}

		// Add both participants
		insertPart := `INSERT INTO chat_participants (chat_id, user_id) VALUES ($1, $2), ($1, $3)`
<<<<<<< HEAD
		log.Printf("Chat id: %s", chatID)

=======
>>>>>>> 36d353e870a3a92512049044059065c65fef7165
		if _, err := tx.Exec(insertPart, chatID, senderID, receiverID); err != nil {
			return "", err
		}
	}

	err = tx.Commit()
	return chatID, err
}
