package repository

import (
	database "websocket_server/config"
)

type ChatRepository interface {
	SetChats(senderID, receiverID, message string) (string, error)
}

type ChatDB struct {
	sqlDB *database.PostgreDB
}

func InitChatRepository(db *database.PostgreDB) *ChatDB {
	return &ChatDB{
		sqlDB: db,
	}
}

func (r *ChatDB) SetChats(senderID, receiverID, message string) (string, error) {
	tx, err := r.sqlDB.Db.Begin()
	if err != nil {
		return "", err
	}
	defer tx.Rollback()

	var chatID string
	// 1. Try to find an existing chat between these two specific people
	findQuery := `
        SELECT chat_id FROM chat_participants 
        WHERE user_id IN ($1, $2) 
        GROUP BY chat_id 
        HAVING COUNT(DISTINCT user_id) = 2
    `
	err = tx.QueryRow(findQuery, senderID, receiverID).Scan(&chatID)

	if err == nil {
		// 2. CHAT EXISTS: Just update the last message
		updateQuery := `UPDATE chats SET last_message = $1, updated_at = NOW() WHERE chat_id = $2`
		if _, err := tx.Exec(updateQuery, message, chatID); err != nil {
			return "", err
		}
	} else {
		// 3. CHAT DOES NOT EXIST: Create everything
		// Note: chat_id is auto-generated by your UUID default in the table
		insertChat := `INSERT INTO chats (last_message) VALUES ($1) RETURNING chat_id`
		if err := tx.QueryRow(insertChat, message).Scan(&chatID); err != nil {
			return "", err
		}

		// Add both participants
		insertPart := `INSERT INTO chat_participants (chat_id, user_id) VALUES ($1, $2), ($1, $3)`
		if _, err := tx.Exec(insertPart, chatID, senderID, receiverID); err != nil {
			return "", err
		}
	}

	err = tx.Commit()
	return chatID, err
}
