package repository

import (
	"log"
	"time"
	database "websocket_server/config"
)

type ChatRepository interface {
	SetChats(senderID, receiverID, message string) (string, error)
	GetChats(userId string) ([]ChatSummary, error)
}

type ChatDB struct {
	sqlDB *database.PostgreDB
}

func InitChatRepository(db *database.PostgreDB) *ChatDB {
	return &ChatDB{
		sqlDB: db,
	}
}

type ChatSummary struct {
	ChatID          string    `json:"chat_id"`
	LastMessage     string    `json:"last_message"`
	LastSenderEmail string    `json:"last_sender_email"`
	LastSenderId    string    `json:"last_sender_id"`
	RecipientEmail  string    `json:"other_user_id"`    // Match your JSON output
	RecipientId     string    `json:"other_user_email"` // Match your JSON output
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (cd *ChatDB) SetChats(senderID, receiverID, message string) (string, error) {
	tx, err := cd.sqlDB.Db.Begin()
	if err != nil {
		return "", err
	}
	defer tx.Rollback()

	var chatID string

	log.Printf("Sender Id: %s\nReceiver Id: %s\n Message: %s", senderID, receiverID, message)

	findQuery := `
        SELECT chat_id FROM chat_participants 
		WHERE chat_id IN (
			SELECT chat_id FROM chat_participants WHERE user_id = $1
		) AND user_id = $2
		GROUP BY chat_id
    `
	err = tx.QueryRow(findQuery, senderID, receiverID).Scan(&chatID)

	if err == nil {
		// 2. CHAT EXISTS: Just update the last message
		updateQuery := `UPDATE chats SET last_message = $1, user_id = $2, updated_at = NOW() WHERE chat_id = $3`
		if _, err := tx.Exec(updateQuery, message, senderID, chatID); err != nil {
			return "", err
		}

	} else {
		// 3. CHAT DOES NOT EXIST: Create everything
		// Note: chat_id is auto-generated by UUID default in the table
		insertChat := `INSERT INTO chats (last_message, user_id) VALUES ($1, $2) RETURNING chat_id`
		if err := tx.QueryRow(insertChat, message, senderID).Scan(&chatID); err != nil {
			return "", err
		}

		// Add both participants
		insertPart := `INSERT INTO chat_participants (chat_id, user_id) VALUES ($1, $2), ($1, $3)`
		log.Printf("Chat id: %s", chatID)

		if _, err := tx.Exec(insertPart, chatID, senderID, receiverID); err != nil {
			return "", err
		}
	}

	err = tx.Commit()
	return chatID, err
}

func (cd *ChatDB) GetChats(userId string) ([]ChatSummary, error) {
	query := `
		SELECT 
			c.chat_id, 
			c.last_message, 
			u_sender.email AS last_sender_email,
			u_sender.user_id AS last_sender_id,
			u_recipient.email AS recipient_email,
			u_recipient.user_id AS recipient_id,
			c.created_at,
			c.updated_at
		FROM chats c
		-- Find MY membership
		JOIN chat_participants cp_me ON c.chat_id = cp_me.chat_id AND cp_me.user_id = $1
		-- Find the OTHER membership (The one that is NOT me)
		JOIN chat_participants cp_other ON c.chat_id = cp_other.chat_id AND cp_other.user_id != $1
		-- Get sender and recipient info
		LEFT JOIN users u_sender ON c.user_id = u_sender.user_id
		LEFT JOIN users u_recipient ON cp_other.user_id = u_recipient.user_id
		ORDER BY c.updated_at DESC;
	`

	rows, err := cd.sqlDB.Db.Query(query, userId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var chats []ChatSummary
	for rows.Next() {
		var s ChatSummary
		if err := rows.Scan(&s.ChatID, &s.LastMessage,
			&s.LastSenderEmail, &s.LastSenderId,
			&s.RecipientEmail, &s.RecipientId,
			&s.CreatedAt, &s.UpdatedAt); err != nil {
			return nil, err
		}
		chats = append(chats, s)
	}

	return chats, nil
}
